{{- if .Values.secrets.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: lightwell-sa
  labels:
    {{- include "demo-lightwell.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ required "lightwell.username is required (edit values.yaml after fork)" .Values.lightwell.username | quote }}
  token: {{ required "lightwell.token is required (edit values.yaml after fork)" .Values.lightwell.token | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: jboss-admin
  labels:
    {{- include "demo-lightwell.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.jbossAdmin.username | quote }}
  password: {{ .Values.jbossAdmin.password | quote }}
{{- if .Values.quay.push }}
---
apiVersion: v1
kind: Secret
metadata:
  name: quay-creds
  labels:
    {{- include "demo-lightwell.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ required "quay.username is required when quay.push=true" .Values.quay.username | quote }}
  password: {{ required "quay.password is required when quay.push=true" .Values.quay.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: quay-pull-secret
  labels:
    {{- include "demo-lightwell.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "demo-lightwell.dockerconfigjson" . }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: lightwell-devspaces-env
  labels:
    {{- include "demo-lightwell.labels" . | nindent 4 }}
    controller.devfile.io/mount-to-devworkspace: "true"
    controller.devfile.io/watch-secret: "true"
  annotations:
    controller.devfile.io/mount-as: env
type: Opaque
stringData:
  LIGHTWELL_USERNAME: {{ .Values.lightwell.username | quote }}
  LIGHTWELL_TOKEN: {{ .Values.lightwell.token | quote }}
  LIGHTWELL_TIER: {{ .Values.lightwell.tier | quote }}
  LIGHTWELL_URL: {{ .Values.nexus.lightwell.remoteUrl | quote }}
  QUAY_IMAGE: {{ .Values.quay.image | quote }}
  INTERNAL_IMAGE: {{ include "demo-lightwell.internalImage" . | quote }}
{{- end }}
