apiVersion: v2
name: devspaces-workspace
description: Helm chart to deploy a DevWorkspace CR for the Lightwell demo, enabling GitOps/Helm-based provisioning of OpenShift Dev Spaces environments.
type: application
version: 0.1.1
appVersion: "1.0.0"
home: https://maximilianopizarro.github.io/demo-lightwell/
icon: https://raw.githubusercontent.com/maximilianoPizarro/demo-lightwell/main/docs/brand/openshift-dev-spaces.svg
keywords:
  - lightwell
  - devspaces
  - workspace
  - openshift
sources:
  - https://github.com/maximilianoPizarro/demo-lightwell
maintainers:
  - name: Maximiliano Pizarro
    email: maximiliano.pizarro.5@gmail.com
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/category: integration-delivery
  artifacthub.io/prerelease: "false"
